export const REQUEST_ACCOUNT_DETAIL = 'REQUEST_ACCOUNT_DETAIL'
export const REQUEST_ACCOUNT_DETAIL_SUCCESS = 'REQUEST_ACCOUNT_DETAIL_SUCCESS'
export const REQUEST_ACCOUNT_DETAIL_FAILED = 'REQUEST_ACCOUNT_DETAIL_FAILED'