export const REQUEST_ACCOUNT_DETAIL = 'REQUEST_ACCOUNT_DETAIL'
export const REQUEST_ACCOUNT_DETAIL_SUCCESS = 'REQUEST_ACCOUNT_DETAIL_SUCCESS'
export const REQUEST_ACCOUNT_DETAIL_FAILED = 'REQUEST_ACCOUNT_DETAIL_FAILED'

export const POST_LOGIN = 'POST_LOGIN'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'