export const BUTTON_PLUS_CLICKED = "BUTTON_PLUS_CLICKED";
export const BUTTON_PLUS_SUCCESS = "BUTTON_PLUS_SUCCESS";
export const BUTTON_PLUS_FAILURE = "BUTTON_PLUS_FAILURE";

export const REQUEST_ACCOUNT_DETAIL = "REQUEST_ACCOUNT_DETAIL"
export const REQUEST_ACCOUNT_DETAIL_SUCCESS = "REQUEST_ACCOUNT_DETAIL_SUCCESS"
export const REQUEST_ACCOUNT_DETAIL_FAILED = "REQUEST_ACCOUNT_DETAIL_FAILED"